refactor: remove company with branches
bakaphp/kanvas-ecosystem-api pull request #1103
Opened 2024-03-21 06:27 UTC by FredPeal

2024-03-22 20:42 UTC, arfenis approved these changes

2024-03-23 00:49 UTC, kaioken requested changes

2024-03-23 00:49 UTC, kaioken commented on src/Kanvas/Companies/Actions/DeleteCompaniesAction.php
> +        DB::transaction(function () use ($companies) {
@FredPeal isn't it better to use cascade ?

2024-03-24 03:44 UTC, kaioken approved these changes

2024-03-29 05:50 UTC, merged