Cad 68
bakaphp/kanvas-ecosystem-api pull request #1515
Opened 2024-06-13 19:54 UTC by FredPeal

2024-06-14 12:02 UTC, kaioken requested changes

2024-06-14 12:02 UTC, kaioken commented on database/migrations/Guild/2024_06_11_215748_peoples_employment_history.php
> +            $table->string('company_employer_name');
@FredPeal change the name to company_name , we already are on the employment history table no need to add employer

2024-06-14 12:02 UTC, kaioken commented on src/Domains/Guild/Customers/Actions/ScreeningAction.php
> +class ScreeningAction
@FredPeal this action goes into a connector domain apollo

2024-06-14 12:02 UTC, kaioken commented on src/Domains/Guild/Customers/Workflows/Activities/ScreeningPeopleActivity.php
> +class ScreeningPeopleActivity extends Activity
@FredPeal this goes into connector

2024-06-14 12:02 UTC, kaioken commented on graphql/schemas/Guild/people.graphql
> +    status: Int!
@FredPeal what are the status ?

2024-06-14 14:18 UTC, FredPeal commented on graphql/schemas/Guild/people.graphql
> +    status: Int!
I going to create a enum

2024-06-14 17:40 UTC, kaioken requested changes

2024-06-14 17:40 UTC, kaioken commented on database/migrations/Guild/2024_06_11_215748_peoples_employment_history.php
> +            $table->date('start_date');
@FredPeal index start date , end date and status, also index for peoples id and apps_id

2024-06-14 17:40 UTC, kaioken commented on graphql/schemas/Guild/people.graphql
> +    peoplesEmploymentHistory: [PeopleEmploymentHistory!]!
change this to employment_history , since we are using _ on the properties

    employment_history: [PeopleEmploymentHistory!]!

2024-06-14 17:40 UTC, kaioken commented on src/Domains/Connectors/Apollo/Workflows/Activities/ScreeningPeopleActivity.php
> +        $people->peoplesEmploymentHistory()->saveMany($history);
@FredPeal will this handle if we send the same date multiple times?

2024-06-14 17:40 UTC, kaioken commented on src/Domains/Guild/Customers/Actions/CreatePeopleAction.php
> +            [
@FredPeal send the app

2024-06-16 03:51 UTC, kaioken requested changes

2024-06-16 03:51 UTC, kaioken commented on graphql/schemas/Guild/people.graphql
> +    peoples_employmentHistory: [PeopleEmploymentHistory!]!
@FredPeal again no need to say people just do `employment_history`

2024-06-16 03:51 UTC, kaioken commented on src/Domains/Connectors/Apollo/Workflows/Activities/ScreeningPeopleActivity.php
> +        $people->peoplesEmploymentHistory()->delete();
@FredPeal again you shouldnt delete thema ll, you don't know if they added any manually , you have to verify and update or create

2024-06-16 03:51 UTC, kaioken commented on src/Domains/Guild/Customers/Models/People.php
> +    public function peoplesEmploymentHistory(): HasMany
@FredPeal again you are inside people just do employment history

2024-06-17 19:05 UTC, kaioken approved these changes

2024-06-17 19:11 UTC, merged