draft: importers
bakaphp/kanvas-ecosystem-api pull request #1802
Opened 2024-08-13 14:15 UTC by FredPeal

2024-08-13 15:22 UTC, arfenis approved these changes

2024-08-20 15:10 UTC, arfenis approved these changes

2024-08-20 16:01 UTC, kaioken requested changes

2024-08-20 16:01 UTC, kaioken commented on src/Kanvas/MappersImportersTemplates/Models/AttributeMapperImporterTemplate.php
> +    protected $table = 'attributes_mappers_importers_templates';
@FredPeal use the new tree library we are using in kanvas     use AsTree;
https://github.com/nevadskiy/laravel-tree

2024-08-21 15:06 UTC, kaioken approved these changes

2024-08-21 15:07 UTC, merged