Update/Create Attribute Type and Is_Required Property
bakaphp/kanvas-ecosystem-api pull request #1896
Opened 2024-09-03 14:19 UTC by Keysie27

2024-09-03 16:27 UTC, kaioken requested changes

2024-09-03 16:27 UTC, kaioken commented on database/migrations/Inventory/2024_09_03_104405_add_is_required_to_attributes_table.php
> +            $table->boolean('is_required')->after('attributes_type_id')->default(false);
@Keysie27 add it as a index also

2024-09-03 16:27 UTC, kaioken commented on database/migrations/Inventory/2024_09_03_104405_add_is_required_to_attributes_table.php
> +            $table->boolean('is_required')->after('attributes_type_id')->default(false);
move it as a draft and add test for future release

2024-10-11 15:35 UTC, rwhite27 commented
@kaioken  is this pr still valid or can i close it?

2025-04-08 03:37 UTC, kaioken approved these changes

2025-04-08 04:34 UTC, merged