Mk 3033 email template mutation
bakaphp/kanvas-ecosystem-api pull request #2276
Opened 2024-10-23 20:26 UTC by rwhite27

## General Description

Add email template and email template variables creation via grapql. This feature is expected for the admin.

## Related Issue

[Add Mutation for Email Template Modification](https://ottoradio.atlassian.net/browse/MK-3033)

## Checklist

A checklist of things that should be done before merging this PR. Linked to the ticket or issue that this PR is related to.(if applicable)

- [x] I have created a mutation for template creation
- [x] I added template variables to a template
- [x] I have created a migration that adds template_id to the email_templates_variables table.

2024-10-23 22:59 UTC, kaioken requested changes

2024-10-23 22:59 UTC, kaioken commented on graphql/schemas/Ecosystem/templates.graphql
> +    users_id: Int!
@rwhite27 no need for the id , use the user object and company object

2024-10-23 22:59 UTC, kaioken commented on graphql/schemas/Ecosystem/templates.graphql
> +    apps_id: Int!
@rwhite27 no need for app

2024-10-23 22:59 UTC, kaioken commented on graphql/schemas/Ecosystem/templates.graphql
> +            scopes: ["fromCompany", "fromApp"]
@rwhite27 add notDeleted scope

2024-10-23 22:59 UTC, kaioken commented on graphql/schemas/Ecosystem/templates.graphql
> +    createOrUpdateTemplate(input: TemplatesInput!): Templates!
@rwhite27 devide create and update even if we use the same method just for verbose

2024-10-24 16:41 UTC, rwhite27 commented on graphql/schemas/Ecosystem/templates.graphql
> +    apps_id: Int!
why not?

2024-10-29 06:19 UTC, FredPeal approved these changes

2024-10-29 21:24 UTC, merged