feat: netsuite connector
bakaphp/kanvas-ecosystem-api pull request #2282
Opened 2024-10-24 19:10 UTC by kaioken

## General Description

Netsuite connector

2024-10-24 19:22 UTC, rwhite27 requested changes

2024-10-24 19:22 UTC, rwhite27 commented on src/Domains/Connectors/NetSuite/Client.php
> +    protected string $apiUrl = 'https://webservices.netsuite.com';
put this as an env variable

2024-10-24 22:37 UTC, FredPeal approved these changes

2024-10-30 16:24 UTC, arfenis approved these changes

2024-10-31 03:59 UTC, merged