check if message has an order attached and check locked status
bakaphp/kanvas-ecosystem-api pull request #2584
Opened 2024-12-03 20:35 UTC by rwhite27

## General Description

Add check order status of content-locked messages. If order is completed set is_locked to false, otherwise, set it to locked. It only applies to messages that have app_module_message records with entities of the Order class.

## Related Issue

https://ottoradio.atlassian.net/browse/MK-3136

2024-12-13 21:15 UTC, FredPeal approved these changes

2024-12-18 02:56 UTC, kaioken requested changes

2024-12-18 02:56 UTC, kaioken commented on src/Domains/Social/Messages/Actions/CreateAppModuleMessageAction.php
> +        $data = [
@rwhite27 firstOrCreate ?

2024-12-18 02:56 UTC, kaioken commented on src/Domains/Social/Messages/Models/Message.php
> +        return (bool)$this->appModuleMessage;
@rwhite27 $this->appModuleMessage->exist();

2024-12-20 11:58 UTC, merged