Add email client
bakaphp/kanvas-ecosystem-api pull request #3
Opened 2022-07-27 15:38 UTC by rwhite27

Features:

- Add filesystem domain
- Add upload action
- Add create filesystem action
- Add filesystem controller

2022-08-04 16:49 UTC, kaioken requested changes

2022-08-04 16:49 UTC, kaioken commented on domains/Companies/Companies/Actions/CreateCompaniesAction.php
> +        $companies->save();
@rwhite27 laravel save saveOrFail we should use it

2022-08-07 02:18 UTC, FredPeal approved these changes

2022-08-09 13:11 UTC, kaioken requested changes

2022-08-09 13:11 UTC, kaioken commented on app/Providers/KanvasAppsProvider.php
> +        if (Schema::hasTable('apps') && Apps::find(1) && (app()->env != 'testing')) {
@rwhite27 !== instead of !=

2022-08-09 13:11 UTC, kaioken commented on domains/Traits/FilesystemAttachTrait.php
> +        print_r($files);
@rwhite27 remove the die?

2022-08-09 13:41 UTC, merged