starting with graphql with locations
bakaphp/kanvas-ecosystem-api pull request #5
Opened 2022-08-07 02:16 UTC by FredPeal

2022-08-08 18:44 UTC, rwhite27 commented on composer.json
> +        "mll-lab/laravel-graphql-playground": "^2.6",
Do we really need this ? @FredPeal

2022-08-09 17:54 UTC, kaioken requested changes

2022-08-09 17:54 UTC, kaioken commented on graphql/schema.graphql
> +#import countries.graphql
@FredPeal move to folder schema

2022-08-12 03:53 UTC, FredPeal commented on composer.json
> +        "mll-lab/laravel-graphql-playground": "^2.6",
nop

2022-08-12 13:32 UTC, kaioken requested changes

2022-08-12 13:32 UTC, kaioken commented on app/GraphQL/Mutations/CreateCountry.php
> +    public function __invoke($_, array $args): Countries
@FredPeal chance args to $request so it easier to understan

2022-08-16 04:27 UTC, kaioken approved these changes

2022-08-16 16:01 UTC, merged