feat: user interactions
bakaphp/kanvas-ecosystem-api pull request #530
Opened 2023-09-11 16:18 UTC by FredPeal

2023-09-11 18:35 UTC, kaioken requested changes

2023-09-11 18:35 UTC, kaioken commented on app/GraphQL/Social/Mutations/UsersInteractions/UsersInteractionsManagement.php
> +    public function disLike($__, array $request): bool
@FredPeal why have 2 function ?

2023-09-11 19:04 UTC, FredPeal commented on graphql/schemas/Social/usersInteractions.graphql
> +        @method(name: "getGroupInteractions")
You do this in Interactions

2023-09-12 14:45 UTC, kaioken approved these changes

2023-09-12 14:46 UTC, merged