Notifications 2.0 test
bakaphp/kanvas-ecosystem-api pull request #646
Opened 2023-11-03 16:49 UTC by rwhite27

2023-11-10 16:46 UTC, FredPeal approved these changes

2023-11-28 04:06 UTC, kaioken requested changes

2023-11-28 04:06 UTC, kaioken commented on app/GraphQL/Ecosystem/Mutations/Notifications/NotificationsManagementMutation.php
> +        $messageType = MessagesTypesRepository::getByVerb($message['metadata']['verb'], $app);
@rwhite27 doesnt this message have any type of structure you can add to a DTO instead of mixed ?

2023-11-28 14:09 UTC, rwhite27 commented on src/Kanvas/Notifications/Actions/BuildPushTemplateNotificationAction.php
> +        ob_start();
If I try to use just the eval for each string without ob_start() and ob_get_clean() the value for each of the variables will be a messy combination of the three strings.

2023-11-28 14:37 UTC, merged