Kn 44
bakaphp/kanvas-ecosystem-api pull request #80
Opened 2022-12-13 18:18 UTC by FredPeal

- [ ] Crud Products
- [ ] Crud Attributes
- [ ] Attach and remove warehouses and categories to products

2022-12-14 04:06 UTC, rwhite27 commented
We should do atomic prs instead of huge ones with lots of files.

2022-12-20 04:21 UTC, kaioken requested changes

2022-12-20 04:21 UTC, kaioken commented on graphql/schemas/Inventory/products.graphql
> +    products_types_id: Int
@FredPeal should you send back the type?

2022-12-20 04:21 UTC, kaioken commented on graphql/schemas/Inventory/products.graphql
> +    updated_at: String
@FredPeal also the product should have its variants

2022-12-30 13:15 UTC, kaioken approved these changes

2022-12-30 13:15 UTC, merged